name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord - Build Start
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "<:neowyze:1195468891724451961> ${{ secrets.GA_APP_NAME }}"
          embed-description: "<a:alert:1187871907895312394> Se solicitó el despliegue en __***producción***__ de una nueva versión"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@${{ secrets.DOKKU_HOST }}/${{ secrets.DOKKU_APP }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: main
          git_push_flags: --force

      - name: Notify Discord - Build Success
        if: ${{ success() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "<:neowyze:1195468891724451961> ${{ secrets.GA_APP_NAME }}"
          embed-color: ${{ secrets.DISCORD_SUCCESS_COLOR }}
          embed-description: "<a:cooldoge:1187872797532364861> Se desplegó exitosamente en __***produccion***__ una nueva versión\n\n**URL:** [www.bdc.agpgroup.com.ar](https://www.bdc.agpgroup.com.ar/)"

      - name: Notify Discord - Build Failure
        if: ${{ failure() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "<:neowyze:1195468891724451961> ${{ secrets.GA_APP_NAME }}"
          embed-color: ${{ secrets.DISCORD_FAILURE_COLOR }}
          embed-description: "<:catshocked:1186138468854796461> Ocurrió un error en el despliegue en __***producción***__"
